### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference when recovering and restart raft

### ISSUE THREAD

**Issue by F21** [hashicorp/raft#261]
I have some code that starts a raft instance then shuts down the instance, perform recovery and then starts a new raft instance. In this situation, it crashes when attempting to recover the cluster.

See the sample program demonstrating the crash below:

```go
package main

import (
	"fmt"
	"io"
	"log"
	"net"
	"os"
	"time"

	"github.com/hashicorp/raft"
)

func main() {

	raftAddr := "127.0.0.1:1111"

	snapshotStore := raft.NewInmemSnapshotStore()

	addr, err := net.ResolveTCPAddr("tcp", raftAddr)

	if err != nil {
		log.Fatal(err)
	}

	trans, err := raft.NewTCPTransport(raftAddr, addr, 3, 10*time.Second, os.Stdout)

	if err != nil {
		log.Fatal(err)
	}

	raftDB := raft.NewInmemStore()

	c := raft.DefaultConfig()
	c.LogOutput = os.Stdout
	c.LocalID = raft.ServerID(raftAddr)

	state := &fsm{}

	r, err := raft.NewRaft(c, state, raftDB, raftDB, snapshotStore, trans)

	if err != nil {
		log.Fatal(err)
	}

	bootstrapConfig := raft.Configuration{
		Servers: []raft.Server{
			{
				Suffrage: raft.Voter,
				ID:       raft.ServerID(raftAddr),
				Address:  raft.ServerAddress(raftAddr),
			},
		},
	}

	f := r.BootstrapCluster(bootstrapConfig)

	if err := f.Error(); err != nil {
		log.Fatalf("error bootstrapping: %s", err)
	}

	ticker := time.NewTicker(10 * time.Second)

	for {

		select {

		case <-ticker.C:

			fmt.Println("simulating live raft restart after 10 secs")

			f = r.Shutdown()

			if f.Error() != nil {
				log.Fatalf("Error shutting down raft: %s", f.Error())
			}

			trans, err = raft.NewTCPTransport(raftAddr, addr, 3, 10*time.Second, os.Stdout)

			fmt.Println("Recovering cluster")

			err = raft.RecoverCluster(c, state, raftDB, raftDB, snapshotStore, trans, raft.Configuration{
				Servers: []raft.Server{
					{
						Suffrage: raft.Voter,
						ID:       raft.ServerID(raftAddr),
						Address:  raft.ServerAddress(raftAddr),
					},
				},
			})

			if err != nil {
				log.Fatalf("Error recovering cluster: %s", err)
			}

			fmt.Println("starting new raft")

			r, err = raft.NewRaft(c, state, raftDB, raftDB, snapshotStore, trans)

			if err != nil {
				log.Fatal(err)
			}

		}
	}
}

type fsm struct {
}

func (f *fsm) Apply(*raft.Log) interface{} {
	return nil
}

func (f *fsm) Snapshot() (raft.FSMSnapshot, error) {
	return &snapshot{}, nil
}

func (f *fsm) Restore(io.ReadCloser) error {
	return nil
}

type snapshot struct {
}

func (s *snapshot) Persist(sink raft.SnapshotSink) error {
	return nil
}

func (s *snapshot) Release() {
	// No-op
}
```

This is the output:
```
2017/11/16 14:58:35 [INFO] raft: Initial configuration (index=0): []
2017/11/16 14:58:35 [INFO] raft: Node at 127.0.0.1:1111 [Follower] entering Follower state (Leader: "")
2017/11/16 14:58:37 [WARN] raft: Heartbeat timeout from "" reached, starting election
2017/11/16 14:58:37 [INFO] raft: Node at 127.0.0.1:1111 [Candidate] entering Candidate state in term 2
2017/11/16 14:58:37 [DEBUG] raft: Votes needed: 1
2017/11/16 14:58:37 [DEBUG] raft: Vote granted from 127.0.0.1:1111 in term 2. Tally: 1
2017/11/16 14:58:37 [INFO] raft: Election won. Tally: 1
2017/11/16 14:58:37 [INFO] raft: Node at 127.0.0.1:1111 [Leader] entering Leader state
simulating live raft restart after 10 secs
Recovering cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x6f677e]

goroutine 1 [running]:
gitlab.com/boostport/rafttest/vendor/github.com/hashicorp/raft.(*NetworkTransport).getProviderAddressOrFallback(0x0, 0x7dea17, 0xe, 0x7dea17, 0xe, 0xc04206fa50, 0x4d2bc2)
       C:/work/rafttest/vendor/github.com/hashicorp/raft/net_transport.go:259 +0x3e
gitlab.com/boostport/rafttest/vendor/github.com/hashicorp/raft.(*NetworkTransport).EncodePeer(0x0, 0x7dea17, 0xe, 0x7dea17, 0xe, 0xc042014180, 0x11, 0x60)
       C:/work/rafttest/vendor/github.com/hashicorp/raft/net_transport.go:403 +0x5e
gitlab.com/boostport/rafttest/vendor/github.com/hashicorp/raft.encodePeers(0xc04218c240, 0x1, 0x1, 0x9a6d60, 0x0, 0xc04203a040, 0xc042024000, 0x7f6ad0)
       C:/work/rafttest/vendor/github.com/hashicorp/raft/configuration.go:286 +0x149
gitlab.com/boostport/rafttest/vendor/github.com/hashicorp/raft.(*InmemSnapshotStore).Create(0xc0421362d0, 0x1, 0x2, 0x2, 0xc04218c240, 0x1, 0x1, 0x1, 0x9a6d60, 0x0, ...)
       C:/work/rafttest/vendor/github.com/hashicorp/raft/inmem_snapshot.go:53 +0x135
gitlab.com/boostport/rafttest/vendor/github.com/hashicorp/raft.RecoverCluster(0xc042156000, 0x9a3c00, 0x9fa120, 0x9a6100, 0xc042138140, 0x9a4700, 0xc042138140, 0x9a3b00, 0xc0421362d0, 0x9a6d60, ...)
       C:/work/rafttest/vendor/github.com/hashicorp/raft/api.go:326 +0x7ce
main.main()
       C:/work/rafttest/tt/main.go:82 +0x939
```

I added some debugging `println`s to the raft library and at some point, `n` (the method receiver) becomes nil in this line: https://github.com/hashicorp/raft/blob/master/net_transport.go#L259

**Comment by F21** [comment]
Closing this as invalid, because it's necessary to shutdown the transport using `transport.Close()` before shutting down raft, otherwise the old transport will still be bound to the port.
