### ISSUE TITLE
The Raft.Shutdown() API can end up in a deadlock

### ISSUE THREAD

**Issue by freeekanayaka** [hashicorp/raft#268]
I've noticed that occasionally some unit tests of [dqlite](https://github.com/CanonicalLtd/dqlite) hang forever.

I **believe** that the reason is a potential deadlock between Raft.Shutdown() and the Raft.runSnapshots() goroutine. The timeline of events looks roughly like:

1. The user calls Raft.Shutdown().Error()
2. Roughly at the same time runSnapshots() decides that it's time to kick Raft.takeSnapshot()
3. The Raft.takeSnapshot() method manages to run a bit and then block on [configReq.Error()](https://github.com/hashicorp/raft/blob/master/snapshot.go#L155) call. This can happen if the shutdown signal is being dispatched to the shutdownCh but it's not quite done, and also the call to ```r.configurationsCh <- configReq``` at line 151 succeeded (because configurationsCh is buffered with size 8), but the future was not actually processed by the main raft goroutine (either runLeader, runCandidate or runFollower)
3. The main goroutine of Raft (either runLeader, runCandidate or runFollower) receives the shutdown signal and exits **without** actually processing the pending request in configurationsCh, hence leaving takeSnapshot blocked.
4. The Error() method of future returned by Raft.Shutdown() is blocked waiting for all raft goroutines to finish, but runSnapshots will never return because it's blocked on takeSnapshot() which is in turn blocked on configReq.Error().

Hope this makes sense.

To see an example of a unit test that failed as above, look [here](https://travis-ci.org/CanonicalLtd/dqlite/builds/331818891#L539).

I'm pasting the relevant Go traceback below as well for reference.

**Comment by freeekanayaka** [comment]
Traceback from the Travis run linked above:

```
2018/01/22 13:57:28 panic: test timed out after 1m0s
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 350 [running]:
2018/01/22 13:57:28 testing.startAlarm.func1()
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:1145 +0xf9
2018/01/22 13:57:28 created by time.goFunc
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/time/sleep.go:170 +0x44
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 1 [chan receive]:
2018/01/22 13:57:28 testing.(*T).Run(0xc420138000, 0x91a0b3, 0x18, 0x930230, 0x481d01)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:790 +0x2fc
2018/01/22 13:57:28 testing.runTests.func1(0xc420138000)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:1004 +0x64
2018/01/22 13:57:28 testing.tRunner(0xc420138000, 0xc42012dd78)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:746 +0xd0
2018/01/22 13:57:28 testing.runTests(0xc4200dabc0, 0xd667c0, 0xe, 0xe, 0x101490100000160)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:1002 +0x2d8
2018/01/22 13:57:28 testing.(*M).Run(0xc42012df18, 0x0)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:921 +0x111
2018/01/22 13:57:28 main.main()
2018/01/22 13:57:28 	github.com/CanonicalLtd/dqlite/internal/replication/_test/_testmain.go:124 +0x1b2
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 5 [syscall]:
2018/01/22 13:57:28 os/signal.signal_recv(0x0)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/sigqueue.go:131 +0xa6
2018/01/22 13:57:28 os/signal.loop()
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/os/signal/signal_unix.go:22 +0x22
2018/01/22 13:57:28 created by os/signal.init.0
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/os/signal/signal_unix.go:28 +0x41
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 262 [semacquire]:
2018/01/22 13:57:28 sync.runtime_Semacquire(0xc4203290cc)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/sema.go:56 +0x39
2018/01/22 13:57:28 sync.(*WaitGroup).Wait(0xc4203290c0)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/sync/waitgroup.go:131 +0x72
2018/01/22 13:57:28 github.com/hashicorp/raft.(*raftState).waitShutdown(0xc420329080)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/hashicorp/raft/state.go:151 +0x31
2018/01/22 13:57:28 github.com/hashicorp/raft.(*shutdownFuture).Error(0xc42000f250, 0xd6e160, 0xc42000f260)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/hashicorp/raft/future.go:158 +0x37
2018/01/22 13:57:28 github.com/CanonicalLtd/raft-test.Shutdown(0xc420138690, 0xc4203414c0, 0x3, 0x3)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/cluster.go:99 +0x150
2018/01/22 13:57:28 github.com/CanonicalLtd/raft-test.Cluster.func1()
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/cluster.go:75 +0x57
2018/01/22 13:57:28 github.com/CanonicalLtd/dqlite/internal/replication_test.runCleanups(0xc4203411c0, 0x4, 0x4)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/dqlite/internal/replication/integration_test.go:279 +0x3a
2018/01/22 13:57:28 github.com/CanonicalLtd/dqlite/internal/replication_test.(*cluster).Cleanup(0xc42015af30)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/dqlite/internal/replication/integration_test.go:233 +0x79
2018/01/22 13:57:28 github.com/CanonicalLtd/dqlite/internal/replication_test.TestIntegration_Snapshot(0xc420138690)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/dqlite/internal/replication/integration_test.go:153 +0x782
2018/01/22 13:57:28 testing.tRunner(0xc420138690, 0x930230)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:746 +0xd0
2018/01/22 13:57:28 created by testing.(*T).Run
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:789 +0x2de
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 88 [chan receive]:
2018/01/22 13:57:28 database/sql.(*DB).connectionOpener(0xc4201fc320)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/database/sql/sql.go:871 +0x53
2018/01/22 13:57:28 created by database/sql.Open
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/database/sql/sql.go:609 +0x1ee
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 266 [chan receive]:
2018/01/22 13:57:28 github.com/hashicorp/raft.(*deferError).Error(0xc42044ec60, 0x0, 0x0)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/hashicorp/raft/future.go:100 +0x75
2018/01/22 13:57:28 github.com/hashicorp/raft.(*Raft).takeSnapshot(0xc420329080, 0x0, 0x0, 0x0, 0x0)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/hashicorp/raft/snapshot.go:155 +0x5f2
2018/01/22 13:57:28 github.com/hashicorp/raft.(*Raft).runSnapshots(0xc420329080)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/hashicorp/raft/snapshot.go:79 +0x40c
2018/01/22 13:57:28 github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/hashicorp/raft/api.go:507 +0x2a
2018/01/22 13:57:28 github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc420329080, 0xc420339600)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/hashicorp/raft/state.go:146 +0x53
2018/01/22 13:57:28 created by github.com/hashicorp/raft.(*raftState).goFunc
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/hashicorp/raft/state.go:144 +0x66
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 165 [chan send]:
2018/01/22 13:57:28 github.com/CanonicalLtd/raft-test.(*NotifyKnob).watch(0xc4202fe1b0)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/notify.go:137 +0x240
2018/01/22 13:57:28 created by github.com/CanonicalLtd/raft-test.(*NotifyKnob).init
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/notify.go:107 +0x1f6
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 105 [chan receive]:
2018/01/22 13:57:28 database/sql.(*DB).connectionOpener(0xc4201fc5a0)
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/database/sql/sql.go:871 +0x53
2018/01/22 13:57:28 created by database/sql.Open
2018/01/22 13:57:28 	/home/travis/.gimme/versions/go1.9.linux.amd64/src/database/sql/sql.go:609 +0x1ee
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 263 [chan send]:
2018/01/22 13:57:28 github.com/CanonicalLtd/raft-test.(*NotifyKnob).watch(0xc4203806c0)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/notify.go:137 +0x240
2018/01/22 13:57:28 created by github.com/CanonicalLtd/raft-test.(*NotifyKnob).init
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/notify.go:107 +0x1f6
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 109 [chan send]:
2018/01/22 13:57:28 github.com/CanonicalLtd/raft-test.(*NotifyKnob).watch(0xc4201f7980)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/notify.go:137 +0x240
2018/01/22 13:57:28 created by github.com/CanonicalLtd/raft-test.(*NotifyKnob).init
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/notify.go:107 +0x1f6
2018/01/22 13:57:28 
2018/01/22 13:57:28 goroutine 179 [chan send]:
2018/01/22 13:57:28 github.com/CanonicalLtd/raft-test.(*NotifyKnob).watch(0xc4202ffd10)
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/notify.go:137 +0x240
2018/01/22 13:57:28 created by github.com/CanonicalLtd/raft-test.(*NotifyKnob).init
2018/01/22 13:57:28 	/home/travis/gopath/src/github.com/CanonicalLtd/raft-test/notify.go:107 +0x1f6
2018/01/22 13:57:28 FAIL	github.com/CanonicalLtd/dqlite/internal/replication	60.026s
2018/01/22 13:57:28 ERROR:exit status 1
```

**Comment by freeekanayaka** [comment]
I think I can confirm the above theory, here's a sample program that eventually reproduces the issue, when run in a loop:

```go
package main

import (
	"context"
	"io"
	"log"
	"time"

	"github.com/hashicorp/raft"
)

func main() {
	// Create a configuration with a very aggressive snapshot cadence
	config := raft.DefaultConfig()
	config.SnapshotInterval = 5 * time.Millisecond
	config.SnapshotThreshold = 1

	config.LocalID = "0"
	config.StartAsLeader = true

	// Create raft dependencies
	store := raft.NewInmemStore()
	snapshot := raft.NewInmemSnapshotStore()
	_, transport := raft.NewInmemTransport("0")
	configuration := raft.Configuration{
		Servers: []raft.Server{{ID: "0", Address: "0"}},
	}
	err := raft.BootstrapCluster(
		config,
		store,
		store,
		snapshot,
		transport,
		configuration,
	)
	if err != nil {
		log.Fatalf("bootstrap error: %v", err)
	}

	// Start the raft instance.
	fsm := &FSM{}
	r, err := raft.NewRaft(
		config,
		fsm,
		store,
		store,
		snapshot,
		transport,
	)
	if err != nil {
		log.Fatalf("start error: %v", err)
	}

	// The raft instance should start as leader
	if r.State() != raft.Leader {
		log.Fatal("raft instance did not start as leader")
	}

	// Apply a few entries to trigger snapshots and then shutdown the node
	// after a bit of time.
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		for i := 0; ; i++ {
			select {
			case <-ctx.Done():
				return
			default:
			}

			if err := r.Apply([]byte{}, time.Second).Error(); err != nil {
				if err != raft.ErrLeadershipLost {
					log.Printf("log command %d failed unexpectedly: %v", i, err)
				}
			}
		}
	}()

	time.Sleep(50 * time.Millisecond)

	// Stop applying logs
	cancel()

	// Wait for graceful shutdown within a timeout
	timeout := time.Second
	future := r.Shutdown()
	errorCh := make(chan error, 0)
	go func() {
		errorCh <- future.Error()
	}()
	select {
	case err := <-errorCh:
		{
			if err != nil {
				log.Fatalf("raft instance did not shutdown cleanly: %v", err)
			}
		}
	case <-time.After(timeout):
		log.Fatalf("raft instances did not shutdown within %s", timeout)
	}
}

// Dummy FSM
type FSM struct{}

func (f *FSM) Apply(*raft.Log) interface{} { return nil }

func (f *FSM) Snapshot() (raft.FSMSnapshot, error) { return &FSMSnapshot{}, nil }

func (f *FSM) Restore(io.ReadCloser) error { return nil }

type FSMSnapshot struct{}

func (s *FSMSnapshot) Persist(sink raft.SnapshotSink) error { return nil }

func (s *FSMSnapshot) Release() {}
```
